#!/bin/bash

# Find the installation directory of Zsh
ZSH_DIR=$(whereis zsh | awk '{print $2}')

# Check if Zsh is installed
if [ -z "$ZSH_DIR" ]; then
    echo "Zsh is not installed."
    exit 1
fi

echo "Zsh is installed at: $ZSH_DIR"

# You can now use $ZSH_DIR in your script
# For example, to run Zsh
$ZSH_DIR --version
