# Generated by interpret_zsh.py — do not edit by hand.

# completion
bindkey '^ ' autosuggest-accept  # Accept autosuggestion

# fzf
bindkey '^[t' fzf-file-widget  # FZF file search

# navigation
bindkey '^[f' forward-word  # Forward word
bindkey '^[b' backward-word  # Backward word

# editing
bindkey '^[d' kill-word  # Kill word forward

# ai
bindkey '^o' _aichat_compose  # Compose command via aichat
bindkey '^[^o' _aichat_repl  # Open aichat REPL

