# aichat — local-first (LM Studio) LLM command generation.
# Two entry points, bound via custom/keybinding/keymap_zsh.yaml:
#   Ctrl+O      → _aichat_compose  (transform current line into a command)
#   Ctrl+Alt+O  → _aichat_repl     (interactive aichat REPL)

# Compose: replace the current command line with a concrete command generated by
# aichat's Shell Assistant (-e/--execute). Adapted from aichat's official
# scripts/shell-integration/integration.zsh (which binds Alt+e); we rebind to
# Ctrl+O via keymap_zsh.yaml. The user reviews the result before pressing Enter.
_aichat_compose() {
    if [[ -n "$BUFFER" ]]; then
        local _old=$BUFFER
        local _new
        BUFFER+="⌛"
        zle -I && zle redisplay
        if _new=$(aichat -e "$_old"); then
            BUFFER="$_new"
        else
            BUFFER="$_old"   # on failure, keep what you typed
        fi
        zle end-of-line
    fi
}
zle -N _aichat_compose

# REPL: release the line editor, run aichat's interactive REPL, then restore the
# prompt on exit (same pattern fzf's widgets use).
_aichat_repl() {
    zle -I
    aichat
    zle reset-prompt
}
zle -N _aichat_repl
